//! DEBT-5 integration test: `atman de --post-hoc tukey` on the
//! shared 3-level fixture used by the sidak test.
//!
//! We cross-validate two ways:
//!
//! 1. **Self-consistency against `atman_core::studentized_range::ptukey`** —
//!    run atman's tukey dispatch to get `(estimate, se, df,
//!    posthoc_adj_p)`, recompute the expected `1 − ptukey(|est|·√2/se,
//!    k, df)` via the shared core function, and verify the numbers
//!    agree to 1e-10. This confirms the dispatch wires the studentized
//!    range into the adjustment correctly — the ≥3-decimal R-parity
//!    contract on `ptukey` itself lives in
//!    `atman-core::studentized_range::tests` and is verified at
//!    canonical critical values (α = 0.05 for k ∈ {3,4,5}).
//!
//! 2. **Magnitude on planted effects** — the fixture plants a strong
//!    stage effect on `RESPONDER` and no effect on `NULLP`. After
//!    Tukey adjustment, `RESPONDER`'s three stage-pair contrasts must
//!    all hit `adj_p < 0.05`; `NULLP`'s must all stay `adj_p > 0.10`.
//!
//! 3. **Optional R parity** — if `fixtures/posthoc_tukey_reference.tsv`
//!    exists (generated by `Rscript posthoc_sidak_reference.R`),
//!    verify atman matches R's `ptukey(q, 3, df)` output to 3e-3.

use std::collections::HashMap;
use std::path::Path;
use std::process::{Command, Output};

use atman_core::studentized_range::{ptukey, qtukey};

fn run_atman(args: &[&str]) -> Output {
    let bin = env!("CARGO_BIN_EXE_atman");
    Command::new(bin).args(args).output().expect("run atman")
}

fn parse_tsv(path: &Path) -> (Vec<String>, Vec<std::collections::HashMap<String, String>>) {
    let text = std::fs::read_to_string(path).unwrap();
    let mut lines = text.lines();
    let header: Vec<String> = lines
        .next()
        .unwrap()
        .split('\t')
        .map(String::from)
        .collect();
    let rows = lines
        .map(|line| {
            header
                .iter()
                .zip(line.split('\t'))
                .map(|(h, c)| (h.clone(), c.to_string()))
                .collect()
        })
        .collect();
    (header, rows)
}

fn copy_fixture_to_canonical(tmp: &Path) -> std::path::PathBuf {
    let input = tmp.join("canonical");
    std::fs::create_dir_all(&input).unwrap();
    let fixtures = Path::new("tests/fixtures");
    for (src, dst) in [
        ("posthoc_sidak_samples.tsv", "samples.tsv"),
        ("posthoc_sidak_proteins.tsv", "proteins.tsv"),
        ("posthoc_sidak_qc_measurements.tsv", "measurements.tsv"),
        ("posthoc_sidak_measurements.tsv", "measurements.tsv"),
    ] {
        std::fs::copy(fixtures.join(src), input.join(dst)).unwrap();
    }
    input
}

#[test]
fn posthoc_tukey_adjustment_is_self_consistent_with_core_ptukey() {
    let tmp = tempfile::tempdir().unwrap();
    let input = copy_fixture_to_canonical(tmp.path());
    let output = tmp.path().join("tukey_out");

    let out = run_atman(&[
        "de",
        "--input-dir",
        input.to_str().unwrap(),
        "--output-dir",
        output.to_str().unwrap(),
        "--test",
        "ols",
        "--design",
        "~ stage + age",
        "--post-hoc",
        "tukey",
        "--post-hoc-factor",
        "stage",
        "--min-pairs",
        "4",
    ]);
    assert!(
        out.status.success(),
        "atman failed:\nstdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&out.stdout),
        String::from_utf8_lossy(&out.stderr)
    );

    let (_, rows) = parse_tsv(&output.join("de_results.tsv"));
    assert!(!rows.is_empty());

    let mut max_selfcheck = 0.0_f64;
    for r in &rows {
        let method = r.get("posthoc_method").cloned().unwrap_or_default();
        assert_eq!(method, "tukey");
        let est: f64 = r["mean_diff"].parse().unwrap_or(f64::NAN);
        let ci_low: f64 = r["ci_low"].parse().unwrap_or(f64::NAN);
        let df: f64 = r["df"].parse().unwrap_or(f64::NAN);
        let atman_adj: f64 = r["posthoc_adj_p"].parse().unwrap_or(f64::NAN);
        if !est.is_finite() || !df.is_finite() {
            continue;
        }
        // Recover SE from the emitted 95% Tukey simultaneous CI:
        // ci_low = est - q*·se/√2, where q* = qtukey(0.95, k=3, df).
        let q_crit = qtukey(0.95, 3, df);
        let se = (est - ci_low) * std::f64::consts::SQRT_2 / q_crit;
        let q = est.abs() * std::f64::consts::SQRT_2 / se;
        // nmeans = 3 (stage has levels AD, CN, MCI).
        let expected_adj = (1.0 - ptukey(q, 3, df)).clamp(0.0, 1.0);
        let drift = (atman_adj - expected_adj).abs();
        max_selfcheck = max_selfcheck.max(drift);
    }
    assert!(
        max_selfcheck < 1e-10,
        "atman's tukey adj_p must match atman_core::ptukey to floating-point precision; \
         max drift = {max_selfcheck:e}"
    );
}

#[test]
fn posthoc_tukey_magnitude_detects_planted_stage_effect() {
    let tmp = tempfile::tempdir().unwrap();
    let input = copy_fixture_to_canonical(tmp.path());
    let output = tmp.path().join("tukey_magnitude");

    let out = run_atman(&[
        "de",
        "--input-dir",
        input.to_str().unwrap(),
        "--output-dir",
        output.to_str().unwrap(),
        "--test",
        "ols",
        "--design",
        "~ stage + age",
        "--post-hoc",
        "tukey",
        "--post-hoc-factor",
        "stage",
        "--min-pairs",
        "4",
    ]);
    assert!(out.status.success());
    let (_, rows) = parse_tsv(&output.join("de_results.tsv"));

    let responder_rows: Vec<&HashMap<String, String>> = rows
        .iter()
        .filter(|r| {
            r.get("gene_symbol")
                .map(|g| g == "RESPONDER")
                .unwrap_or(false)
        })
        .collect();
    let null_rows: Vec<&HashMap<String, String>> = rows
        .iter()
        .filter(|r| r.get("gene_symbol").map(|g| g == "NULLP").unwrap_or(false))
        .collect();
    assert_eq!(responder_rows.len(), 3, "expected 3 pairs for RESPONDER");
    assert_eq!(null_rows.len(), 3, "expected 3 pairs for NULLP");
    for r in &responder_rows {
        let adj: f64 = r["posthoc_adj_p"].parse().unwrap();
        assert!(
            adj < 0.05,
            "planted strong effect should be Tukey-significant: {:?} adj={adj}",
            r["comparison"]
        );
    }
    for r in &null_rows {
        let adj: f64 = r["posthoc_adj_p"].parse().unwrap();
        assert!(
            adj > 0.10,
            "planted null should not be Tukey-significant: {:?} adj={adj}",
            r["comparison"]
        );
    }
}

#[test]
fn posthoc_tukey_matches_r_reference_if_available() {
    // Optional: skipped when the R-generated reference doesn't exist
    // (i.e. on CI without R). Developer-facing verification.
    let ref_path = Path::new("tests/fixtures/posthoc_tukey_reference.tsv");
    if !ref_path.exists() {
        eprintln!("skip: posthoc_tukey_reference.tsv absent; run Rscript to generate");
        return;
    }
    let tmp = tempfile::tempdir().unwrap();
    let input = copy_fixture_to_canonical(tmp.path());
    let output = tmp.path().join("tukey_parity");
    let out = run_atman(&[
        "de",
        "--input-dir",
        input.to_str().unwrap(),
        "--output-dir",
        output.to_str().unwrap(),
        "--test",
        "ols",
        "--design",
        "~ stage + age",
        "--post-hoc",
        "tukey",
        "--post-hoc-factor",
        "stage",
        "--min-pairs",
        "4",
    ]);
    assert!(out.status.success());
    let (_, atman_rows) = parse_tsv(&output.join("de_results.tsv"));
    let (_, ref_rows) = parse_tsv(ref_path);
    type Key = (String, String);
    let atman_by_key: HashMap<Key, &HashMap<String, String>> = atman_rows
        .iter()
        .map(|r| ((r["gene_symbol"].clone(), r["comparison"].clone()), r))
        .collect();
    let mut max_adj_err = 0.0_f64;
    for ref_row in &ref_rows {
        let key = (
            ref_row["gene_symbol"].clone(),
            ref_row["comparison"].clone(),
        );
        let atman_row = atman_by_key
            .get(&key)
            .unwrap_or_else(|| panic!("atman missing row for {key:?}"));
        let ref_adj: f64 = ref_row["posthoc_adj_p"].parse().unwrap();
        let atman_adj: f64 = atman_row["posthoc_adj_p"].parse().unwrap();
        max_adj_err = max_adj_err.max((ref_adj - atman_adj).abs());
    }
    eprintln!("tukey R parity: max |Δadj_p| = {max_adj_err:.3e}");
    assert!(
        max_adj_err < 3e-3,
        "tukey adj_p drifts from R reference by {max_adj_err:e}"
    );
}
