#!/usr/bin/env Rscript
# crates/atman/tests/fixtures/de_adjust_for_limma_reference.R
#
# Reads measurements + samples + covariates from the fixture directories,
# fits limma with model.matrix(~ condition + nmf_program_01 + nmf_program_02),
# emits topTable for every gene as:
#   gene_symbol\tlog_fc\tt_stat\tp_value\tq_value
#
# Pinned: limma 3.66.0, R 4.5.0+
# Coefficient tested: "conditionb" (the condition contrast, B vs A)
#
# Sign convention: limma's "conditionb" coefficient is mean_b − mean_a.
# atman's A-B comparison is mean_a − mean_b (contrast [0, -1, 0, 0]).
# The reference TSV records limma-native sign (mean_b − mean_a) so the
# integration test is responsible for negating when checking against atman.
#
# Usage:
#   Rscript de_adjust_for_limma_reference.R \
#     <input_dir> <covariates_tsv> <output_tsv>

suppressPackageStartupMessages(library(limma))

args <- commandArgs(trailingOnly = TRUE)
if (length(args) != 3) {
  stop("usage: Rscript de_adjust_for_limma_reference.R <input_dir> <covariates_tsv> <output_tsv>")
}
input_dir      <- args[1]
covariates_tsv <- args[2]
output_tsv     <- args[3]

# ── read inputs ───────────────────────────────────────────────────────────────
read_tsv_skip_comment <- function(path) {
  # Skip leading "#" comment line if present.
  raw <- readLines(path)
  body <- raw[!startsWith(raw, "#")]
  read.table(text = paste(body, collapse = "\n"),
             sep = "\t", header = TRUE, stringsAsFactors = FALSE,
             check.names = FALSE, quote = "")
}

samples      <- read_tsv_skip_comment(file.path(input_dir, "samples.tsv"))
measurements <- read_tsv_skip_comment(file.path(input_dir, "measurements.tsv"))
covariates   <- read_tsv_skip_comment(covariates_tsv)

# ── build wide expression matrix (genes × samples) ────────────────────────────
# Keep only non-control samples (is_control == 0) that have a condition.
samples <- samples[samples$is_control == 0 & !is.na(samples$condition), ]
# Retain only the samples present in the fixture (all 12, no controls here).
sample_ids_ordered <- samples$sample_id

# Pivot measurements to matrix.
# gene_symbol → rows; sample_id → cols.
genes   <- sort(unique(measurements$gene_symbol))
n_genes <- length(genes)
n_samp  <- length(sample_ids_ordered)

y <- matrix(NA_real_, nrow = n_genes, ncol = n_samp,
            dimnames = list(genes, sample_ids_ordered))
for (i in seq_len(nrow(measurements))) {
  g   <- measurements$gene_symbol[i]
  sid <- measurements$sample_id[i]
  if (sid %in% sample_ids_ordered && g %in% genes) {
    y[g, sid] <- as.numeric(measurements$abundance[i])
  }
}

# ── design matrix ─────────────────────────────────────────────────────────────
# Join covariates onto samples (wide format: sample_id | nmf_program_01 | nmf_program_02).
rownames(covariates) <- covariates$sample_id
cov_mat <- covariates[sample_ids_ordered, c("nmf_program_01", "nmf_program_02"), drop = FALSE]

condition <- factor(samples$condition[match(sample_ids_ordered, samples$sample_id)],
                    levels = c("a", "b"))

design <- model.matrix(~ condition + nmf_program_01 + nmf_program_02,
                       data = data.frame(
                         condition      = condition,
                         nmf_program_01 = cov_mat$nmf_program_01,
                         nmf_program_02 = cov_mat$nmf_program_02
                       ))

# ── limma fit ─────────────────────────────────────────────────────────────────
fit <- lmFit(y, design)
fit <- eBayes(fit, trend = FALSE, robust = FALSE)

# ── topTable for all genes ────────────────────────────────────────────────────
# coef = "conditionb" — the B vs A contrast coefficient.
tt <- topTable(fit, coef = "conditionb", number = Inf, sort.by = "none",
               adjust.method = "BH")

# ── emit reference TSV ────────────────────────────────────────────────────────
out <- data.frame(
  gene_symbol = rownames(tt),
  log_fc      = tt$logFC,
  t_stat      = tt$t,
  p_value     = tt$P.Value,
  q_value     = tt$adj.P.Val,
  stringsAsFactors = FALSE
)

limma_ver <- as.character(packageVersion("limma"))
r_ver     <- paste(R.version$major, R.version$minor, sep = ".")
header_comment <- paste0(
  "# generated by de_adjust_for_limma_reference.R",
  " limma=", limma_ver,
  " R=", r_ver,
  " coef=conditionb sign=mean_b_minus_mean_a"
)

# Write with a leading comment line (atman's reader skips '#' lines).
con <- file(output_tsv, open = "w")
writeLines(header_comment, con)
write.table(out, con, sep = "\t", quote = FALSE, row.names = FALSE)
close(con)

cat(sprintf("wrote %s (%d genes)\n", output_tsv, nrow(out)))
cat(sprintf("limma %s, R %s\n", limma_ver, r_ver))
cat(sprintf("design columns: %s\n", paste(colnames(design), collapse = ", ")))
