#!/usr/bin/env Rscript
# crates/atman/tests/fixtures/de_adjust_for_ols_reference.R
#
# K4 reference: OLS with covariates.
#
# Per-protein model: lm(abundance ~ condition + nmf_program_01 + nmf_program_02)
# Coefficient tested: "conditionb" (condition b vs a; mean_b - mean_a)
#
# Sign convention: R's "conditionb" = mean_b - mean_a.
# atman --groups b-a: effect = mean_b - mean_a (same sign, no flip needed).
#
# Emits: gene_symbol\tlog_fc\tt_stat\tp_value\tq_value
# q_value = BH-adjusted p across all genes (same family as atman).
#
# Pinned: base R lm, R 4.5.0+
#
# Usage:
#   Rscript de_adjust_for_ols_reference.R <input_dir> <covariates_tsv> <output_tsv>

args <- commandArgs(trailingOnly = TRUE)
if (length(args) != 3) {
  stop("usage: Rscript de_adjust_for_ols_reference.R <input_dir> <covariates_tsv> <output_tsv>")
}
input_dir      <- args[1]
covariates_tsv <- args[2]
output_tsv     <- args[3]

read_tsv_skip_comment <- function(path) {
  raw  <- readLines(path)
  body <- raw[!startsWith(raw, "#")]
  read.table(text = paste(body, collapse = "\n"),
             sep = "\t", header = TRUE, stringsAsFactors = FALSE,
             check.names = FALSE, quote = "")
}

samples      <- read_tsv_skip_comment(file.path(input_dir, "samples.tsv"))
measurements <- read_tsv_skip_comment(file.path(input_dir, "measurements.tsv"))
covariates   <- read_tsv_skip_comment(covariates_tsv)

# Non-control samples with a condition
samples <- samples[samples$is_control == 0 & !is.na(samples$condition), ]
sample_ids <- samples$sample_id

# Join covariates
rownames(covariates) <- covariates$sample_id
cov_mat <- covariates[sample_ids, c("nmf_program_01", "nmf_program_02"), drop = FALSE]

condition <- factor(samples$condition[match(sample_ids, samples$sample_id)],
                    levels = c("a", "b"))

df_design <- data.frame(
  sample_id      = sample_ids,
  condition      = condition,
  nmf_program_01 = cov_mat$nmf_program_01,
  nmf_program_02 = cov_mat$nmf_program_02,
  stringsAsFactors = FALSE
)

genes <- sort(unique(measurements$gene_symbol))

results <- lapply(genes, function(g) {
  vals <- numeric(length(sample_ids))
  names(vals) <- sample_ids
  for (i in seq_len(nrow(measurements))) {
    if (measurements$gene_symbol[i] == g && measurements$sample_id[i] %in% sample_ids) {
      vals[measurements$sample_id[i]] <- as.numeric(measurements$abundance[i])
    }
  }
  df <- df_design
  df$y <- vals[df$sample_id]

  fit <- lm(y ~ condition + nmf_program_01 + nmf_program_02, data = df)
  cf  <- summary(fit)$coefficients
  # "conditionb" = mean_b - mean_a
  row <- cf["conditionb", ]
  list(
    gene_symbol = g,
    log_fc      = row["Estimate"],
    t_stat      = row["t value"],
    p_value     = row["Pr(>|t|)"]
  )
})

res_df <- do.call(rbind, lapply(results, as.data.frame))
res_df$q_value <- p.adjust(res_df$p_value, method = "BH")

r_ver <- paste(R.version$major, R.version$minor, sep = ".")
header_comment <- paste0(
  "# generated by de_adjust_for_ols_reference.R",
  " R=", r_ver,
  " model=lm(y~condition+nmf_program_01+nmf_program_02)",
  " coef=conditionb sign=mean_b_minus_mean_a"
)

con <- file(output_tsv, open = "w")
writeLines(header_comment, con)
write.table(res_df, con, sep = "\t", quote = FALSE, row.names = FALSE)
close(con)

cat(sprintf("wrote %s (%d genes)\n", output_tsv, nrow(res_df)))
cat(sprintf("R %s\n", r_ver))
