#!/usr/bin/env Rscript
# crates/atman/tests/fixtures/de_adjust_for_paired_t_reference.R
#
# K7 reference: paired-t with covariates via per-subject difference regression.
#
# DESIGN CHOICE: paired-t does not natively accept covariates (it operates
# on pairwise differences). When covariates are subject-level constants, the
# standard approach is to regress paired differences on covariate differences:
#   diff_g_k = abundance_b_k - abundance_a_k  (per subject k)
#   covariate_diff_k = cov_b_k - cov_a_k
#   lm(diff ~ covariate_diff_nmf1 + covariate_diff_nmf2) per protein
#   Intercept = adjusted mean paired difference (= log_fc)
#   t from intercept coefficient
#
# This is equivalent to the paired ANCOVA in difference form.
#
# Uses the PAIRED fixture (24 samples: 12 subjects × 2 conditions).
# Subjects matched by subject_id.
#
# Sign convention: diff = b - a, so positive log_fc = mean_b > mean_a.
# atman --groups b-a: effect = mean_b - mean_a (same sign, no flip).
#
# Emits: gene_symbol\tlog_fc\tt_stat\tp_value\tq_value
# q_value = BH-adjusted p across all genes.
#
# Pinned: base R lm, R 4.5.0+
#
# Usage:
#   Rscript de_adjust_for_paired_t_reference.R \
#     <paired_input_dir> <paired_covariates_tsv> <output_tsv>

args <- commandArgs(trailingOnly = TRUE)
if (length(args) != 3) {
  stop("usage: Rscript de_adjust_for_paired_t_reference.R <paired_input_dir> <paired_covariates_tsv> <output_tsv>")
}
input_dir      <- args[1]
covariates_tsv <- args[2]
output_tsv     <- args[3]

read_tsv_skip_comment <- function(path) {
  raw  <- readLines(path)
  body <- raw[!startsWith(raw, "#")]
  read.table(text = paste(body, collapse = "\n"),
             sep = "\t", header = TRUE, stringsAsFactors = FALSE,
             check.names = FALSE, quote = "")
}

samples      <- read_tsv_skip_comment(file.path(input_dir, "samples.tsv"))
measurements <- read_tsv_skip_comment(file.path(input_dir, "measurements.tsv"))
covariates   <- read_tsv_skip_comment(covariates_tsv)

samples <- samples[samples$is_control == 0 & !is.na(samples$condition), ]

# Build per-subject covariate difference: (b - a) for each NMF covariate
rownames(covariates) <- covariates$sample_id

# Identify paired samples
samp_a <- samples[samples$condition == "a", ]
samp_b <- samples[samples$condition == "b", ]

# Match by subject_id
subjects <- intersect(samp_a$subject_id, samp_b$subject_id)
subjects <- sort(subjects)

# For each subject: a sample and b sample
get_sample_id <- function(subj, cond_df) {
  cond_df$sample_id[cond_df$subject_id == subj]
}

sid_a <- sapply(subjects, get_sample_id, cond_df = samp_a)
sid_b <- sapply(subjects, get_sample_id, cond_df = samp_b)

# Covariate differences: b - a per subject
nmf1_diff <- as.numeric(covariates[sid_b, "nmf_program_01"]) -
             as.numeric(covariates[sid_a, "nmf_program_01"])
nmf2_diff <- as.numeric(covariates[sid_b, "nmf_program_02"]) -
             as.numeric(covariates[sid_a, "nmf_program_02"])

df_design <- data.frame(
  subject_id     = subjects,
  sid_a          = sid_a,
  sid_b          = sid_b,
  nmf1_diff      = nmf1_diff,
  nmf2_diff      = nmf2_diff,
  stringsAsFactors = FALSE
)

genes <- sort(unique(measurements$gene_symbol))

# Index measurements for fast lookup
meas_by_sid <- split(measurements, measurements$sample_id)

results <- lapply(genes, function(g) {
  # For each subject: diff = abundance_b - abundance_a
  diff_vals <- numeric(nrow(df_design))
  for (j in seq_len(nrow(df_design))) {
    ma <- meas_by_sid[[df_design$sid_a[j]]]
    mb <- meas_by_sid[[df_design$sid_b[j]]]
    va <- as.numeric(ma$abundance[ma$gene_symbol == g])
    vb <- as.numeric(mb$abundance[mb$gene_symbol == g])
    diff_vals[j] <- if (length(vb) == 1 && length(va) == 1) vb - va else NA_real_
  }

  df <- data.frame(
    diff      = diff_vals,
    nmf1_diff = df_design$nmf1_diff,
    nmf2_diff = df_design$nmf2_diff
  )
  df <- df[complete.cases(df), ]

  fit <- lm(diff ~ nmf1_diff + nmf2_diff, data = df)
  cf  <- summary(fit)$coefficients
  row <- cf["(Intercept)", ]
  list(
    gene_symbol = g,
    log_fc      = row["Estimate"],
    t_stat      = row["t value"],
    p_value     = row["Pr(>|t|)"]
  )
})

res_df <- do.call(rbind, lapply(results, as.data.frame))
res_df$q_value <- p.adjust(res_df$p_value, method = "BH")

r_ver <- paste(R.version$major, R.version$minor, sep = ".")
header_comment <- paste0(
  "# generated by de_adjust_for_paired_t_reference.R",
  " R=", r_ver,
  " model=lm(diff~nmf1_diff+nmf2_diff) intercept=adjusted_mean_paired_diff",
  " sign=mean_b_minus_mean_a"
)

con <- file(output_tsv, open = "w")
writeLines(header_comment, con)
write.table(res_df, con, sep = "\t", quote = FALSE, row.names = FALSE)
close(con)

cat(sprintf("wrote %s (%d genes)\n", output_tsv, nrow(res_df)))
cat(sprintf("R %s\n", r_ver))
cat(sprintf("n_subjects=%d\n", length(subjects)))
