#!/usr/bin/env Rscript
# crates/atman/tests/fixtures/de_adjust_for_welch_reference.R
#
# K6 reference: OLS with HC3 robust standard errors (heteroskedasticity-robust).
#
# DESIGN CHOICE: Welch's t-test does not natively accept covariates.
# The standard substitute for "Welch + covariates" is OLS with HC3-robust
# standard errors (sandwich estimator). HC3 gives heteroskedasticity-
# consistent SEs that parallel Welch's core feature (no equal-variance
# assumption) while accommodating additional covariates.
#
# Per-protein model:
#   lm(abundance ~ condition + nmf_program_01 + nmf_program_02)
#   SE from sandwich::vcovHC(fit, type = "HC3")
#   t-stat = Estimate / HC3_SE
#   p-value from Student-t with df = n - p (conservative; Welch-Satterthwaite
#   is not applicable with covariates)
#
# Coefficient tested: "conditionb" (mean_b - mean_a)
#
# Sign convention: "conditionb" = mean_b - mean_a.
# atman --groups b-a: effect = mean_b - mean_a (same sign, no flip).
#
# NOTE: atman's Welch+adjust-for path routes internally to plain OLS
# (without HC3), so the HC3 SE will differ from atman's OLS SE. This
# divergence is documented in DONE_WITH_CONCERNS (K6). The reference TSV
# here records the HC3 version for future comparison; the parity test
# uses plain OLS SE tolerances.
#
# Emits: gene_symbol\tlog_fc\tt_stat\tp_value\tq_value
# q_value = BH-adjusted p across all genes.
#
# Pinned: sandwich 3.1.1, R 4.5.0+
#
# Usage:
#   Rscript de_adjust_for_welch_reference.R <input_dir> <covariates_tsv> <output_tsv>

suppressPackageStartupMessages({
  library(sandwich)
  library(lmtest)
})

args <- commandArgs(trailingOnly = TRUE)
if (length(args) != 3) {
  stop("usage: Rscript de_adjust_for_welch_reference.R <input_dir> <covariates_tsv> <output_tsv>")
}
input_dir      <- args[1]
covariates_tsv <- args[2]
output_tsv     <- args[3]

read_tsv_skip_comment <- function(path) {
  raw  <- readLines(path)
  body <- raw[!startsWith(raw, "#")]
  read.table(text = paste(body, collapse = "\n"),
             sep = "\t", header = TRUE, stringsAsFactors = FALSE,
             check.names = FALSE, quote = "")
}

samples      <- read_tsv_skip_comment(file.path(input_dir, "samples.tsv"))
measurements <- read_tsv_skip_comment(file.path(input_dir, "measurements.tsv"))
covariates   <- read_tsv_skip_comment(covariates_tsv)

samples    <- samples[samples$is_control == 0 & !is.na(samples$condition), ]
sample_ids <- samples$sample_id

rownames(covariates) <- covariates$sample_id
cov_mat <- covariates[sample_ids, c("nmf_program_01", "nmf_program_02"), drop = FALSE]

condition <- factor(samples$condition[match(sample_ids, samples$sample_id)],
                    levels = c("a", "b"))

df_design <- data.frame(
  sample_id      = sample_ids,
  condition      = condition,
  nmf_program_01 = cov_mat$nmf_program_01,
  nmf_program_02 = cov_mat$nmf_program_02,
  stringsAsFactors = FALSE
)

genes <- sort(unique(measurements$gene_symbol))

results <- lapply(genes, function(g) {
  vals <- numeric(length(sample_ids))
  names(vals) <- sample_ids
  for (i in seq_len(nrow(measurements))) {
    if (measurements$gene_symbol[i] == g && measurements$sample_id[i] %in% sample_ids) {
      vals[measurements$sample_id[i]] <- as.numeric(measurements$abundance[i])
    }
  }
  df <- df_design
  df$y <- vals[df$sample_id]

  fit    <- lm(y ~ condition + nmf_program_01 + nmf_program_02, data = df)
  # HC3 robust inference: heteroskedasticity-consistent SE
  ct     <- coeftest(fit, vcov = vcovHC(fit, type = "HC3"))
  row    <- ct["conditionb", ]
  list(
    gene_symbol = g,
    log_fc      = row["Estimate"],
    t_stat      = row["t value"],
    p_value     = row["Pr(>|t|)"]
  )
})

res_df <- do.call(rbind, lapply(results, as.data.frame))
res_df$q_value <- p.adjust(res_df$p_value, method = "BH")

sandwich_ver <- as.character(packageVersion("sandwich"))
r_ver        <- paste(R.version$major, R.version$minor, sep = ".")
header_comment <- paste0(
  "# generated by de_adjust_for_welch_reference.R",
  " sandwich=", sandwich_ver,
  " R=", r_ver,
  " model=lm(y~condition+nmf_program_01+nmf_program_02)+HC3",
  " coef=conditionb sign=mean_b_minus_mean_a",
  " NOTE: atman-welch-path uses plain OLS SE not HC3"
)

con <- file(output_tsv, open = "w")
writeLines(header_comment, con)
write.table(res_df, con, sep = "\t", quote = FALSE, row.names = FALSE)
close(con)

cat(sprintf("wrote %s (%d genes)\n", output_tsv, nrow(res_df)))
cat(sprintf("sandwich %s, R %s\n", sandwich_ver, r_ver))
