#!/usr/bin/env python3
# crates/atman/tests/fixtures/de_adjust_for_setup.py
# generated by: Phase J fixture generator
#
# Writes canonical input TSVs for the --adjust-for limma parity test.
# Usage:
#   python3 de_adjust_for_setup.py <input_dir> <covariates_tsv>
#
# Design:
#   12 samples (6 condition_a + 6 condition_b)
#   30 proteins
#   2 numeric covariates per sample: nmf_program_01, nmf_program_02
#
#   Synthetic abundance model:
#     abundance[g, i] = beta_g * condition_indicator_i
#                     + gamma_g * nmf1_i
#                     + delta_g * nmf2_i
#                     + noise[g, i]
#
#   - Proteins 1–10:  beta_g = 2.0  (true DE, strong)
#   - Proteins 11–20: gamma_g = 3.0 (admixture-driven; not real DE)
#   - Proteins 21–30: delta_g = 2.5 (admixture-driven; not real DE)
#   All proteins share sigma = 0.3 Gaussian noise.
#
#   Seeds are pinned so output is deterministic across Python versions.

import sys
import os
import hashlib
import random
import math

# ── reproducibility ───────────────────────────────────────────────────────────
SEED_NOISE = 20260429
SEED_NMF   = 20260430

N_SAMPLES   = 12
N_A         = 6   # condition_a samples
N_B         = 6   # condition_b samples
N_PROTEINS  = 30

BASELINE    = 8.0   # log2 abundance baseline (keeps values in positive range)
SIGMA_NOISE = 0.30  # per-cell Gaussian noise SD

# ── NMF covariate generation ──────────────────────────────────────────────────
rng_nmf = random.Random(SEED_NMF)

# Covariates are uniform [0, 1]; not correlated with condition to keep the
# design interpretable. Small positive correlation is fine since noise hides it.
nmf1 = [rng_nmf.random() for _ in range(N_SAMPLES)]
nmf2 = [rng_nmf.random() for _ in range(N_SAMPLES)]

# ── protein effect coefficients ───────────────────────────────────────────────
# beta  = condition effect (mean_b - mean_a on log2 scale)
# gamma = nmf1 loading
# delta = nmf2 loading
def make_effects():
    betas  = [0.0] * N_PROTEINS
    gammas = [0.0] * N_PROTEINS
    deltas = [0.0] * N_PROTEINS
    for g in range(N_PROTEINS):
        if g < 10:
            betas[g]  = 2.0      # true DE
        elif g < 20:
            gammas[g] = 3.0      # admixture-driven only
        else:
            deltas[g] = 2.5      # admixture-driven only
    return betas, gammas, deltas

betas, gammas, deltas = make_effects()

# ── abundance matrix ──────────────────────────────────────────────────────────
condition = ["a"] * N_A + ["b"] * N_B   # a=0, b=1

rng_noise = random.Random(SEED_NOISE)

def gauss(mu, sigma):
    # Box-Muller so we don't depend on random.gauss implementation details
    while True:
        u = rng_noise.random()
        v = rng_noise.random()
        if u > 0.0:
            break
    z = math.sqrt(-2.0 * math.log(u)) * math.cos(2.0 * math.pi * v)
    return mu + sigma * z

abundance = []   # [protein][sample]
for g in range(N_PROTEINS):
    row = []
    for i in range(N_SAMPLES):
        cond_ind = 1.0 if condition[i] == "b" else 0.0
        mu = BASELINE + betas[g] * cond_ind + gammas[g] * nmf1[i] + deltas[g] * nmf2[i]
        row.append(gauss(mu, SIGMA_NOISE))
    abundance.append(row)

# ── write files ───────────────────────────────────────────────────────────────

def python_versions():
    import sys
    return f"Python {sys.version.split()[0]}"

def write_tsv(path, header, rows):
    with open(path, "w") as f:
        f.write("# generated by de_adjust_for_setup.py " + python_versions() + "\n")
        f.write("\t".join(header) + "\n")
        for row in rows:
            f.write("\t".join(str(x) for x in row) + "\n")


def main():
    if len(sys.argv) != 3:
        print(f"usage: {sys.argv[0]} <input_dir> <covariates_tsv>", file=sys.stderr)
        sys.exit(1)

    input_dir      = sys.argv[1]
    covariates_tsv = sys.argv[2]

    os.makedirs(input_dir, exist_ok=True)

    # ── samples.tsv ──────────────────────────────────────────────────────────
    sample_ids = [f"S{i+1:02d}" for i in range(N_SAMPLES)]
    samples_header = ["sample_id", "subject_id", "condition", "is_control",
                      "sample_type", "ingest_order"]
    samples_rows = []
    for i, sid in enumerate(sample_ids):
        samples_rows.append([sid, sid, condition[i], 0, "plasma", i + 1])
    write_tsv(os.path.join(input_dir, "samples.tsv"), samples_header, samples_rows)

    # ── proteins.tsv ─────────────────────────────────────────────────────────
    proteins_header = ["platform", "assay_id", "uniprot", "gene_symbol", "panel", "panel_lot"]
    proteins_rows = []
    for g in range(N_PROTEINS):
        proteins_rows.append([
            "olink_explore_ngs",
            f"A{g+1:03d}",
            f"Q{g+1:05d}",
            f"PROT{g+1:03d}",
            "P1",
            "",
        ])
    write_tsv(os.path.join(input_dir, "proteins.tsv"), proteins_header, proteins_rows)

    # ── measurements.tsv ─────────────────────────────────────────────────────
    meas_header = [
        "platform", "sample_id", "assay_id", "gene_symbol", "panel",
        "npx_source_str", "abundance", "abundance_raw", "abundance_unit",
        "qc_sample", "qc_assay", "detection_limit", "below_lod",
        "dropped_by_qc", "plate_id", "panel_lot", "ingest_order",
    ]
    meas_rows = []
    order = 0
    for g in range(N_PROTEINS):
        for i, sid in enumerate(sample_ids):
            order += 1
            v = abundance[g][i]
            meas_rows.append([
                "olink_explore_ngs",
                sid,
                f"A{g+1:03d}",
                f"PROT{g+1:03d}",
                "P1",
                f"{v:.6f}",
                f"{v:.6f}",
                f"{v:.6f}",
                "log2_npx",
                "PASS",
                "PASS",
                "",
                0,
                0,
                "",
                "",
                order,
            ])
    write_tsv(os.path.join(input_dir, "measurements.tsv"), meas_header, meas_rows)

    # ── covariates.tsv ───────────────────────────────────────────────────────
    cov_header = ["sample_id", "nmf_program_01", "nmf_program_02"]
    cov_rows = []
    for i, sid in enumerate(sample_ids):
        cov_rows.append([sid, f"{nmf1[i]:.8f}", f"{nmf2[i]:.8f}"])
    write_tsv(covariates_tsv, cov_header, cov_rows)

    print(f"wrote {input_dir}/samples.tsv ({N_SAMPLES} samples)")
    print(f"wrote {input_dir}/proteins.tsv ({N_PROTEINS} proteins)")
    print(f"wrote {input_dir}/measurements.tsv ({order} rows)")
    print(f"wrote {covariates_tsv} ({N_SAMPLES} rows)")


if __name__ == "__main__":
    main()
