"""Generate MNAR ground-truth with abundance-conditional dropout.

Two non-Gaussian sources mixed into 50 features over 60 samples.
Detection probability follows a logistic of log-abundance:
    P(detected | log_abundance) = 1 / (1 + exp(-(beta0 + beta1 * log_abundance)))
with beta0=4.0, beta1=1.5 (positive coefficient: high abundance -> high detection).
The ground-truth coefficients are committed alongside so atman's recovered
fit can be checked against them.

Outputs:
  argv[1]: mnar_ground_truth_sources.tsv (sample_id, source, value)
  argv[2]: mnar_observed_abundance.tsv (sample_id, gene_symbol, abundance)
            with NaN where below detection
  argv[3]: mnar_detection_mask.tsv (sample_id, gene_symbol, detected)
  argv[4]: mnar_ground_truth_curve.tsv (a single-row TSV: beta0\tbeta1\n4.0\t1.5)

Header: # generated by python <ver> numpy <ver> seed=7 beta0=4.0 beta1=1.5
"""
import sys, platform
import numpy as np

rng = np.random.default_rng(7)
n, p = 60, 50
s1 = rng.uniform(-1, 1, n)
s2 = rng.exponential(1.0, n) - 1.0
A = np.zeros((p, 2))
A[:p//2, 0] = 1.0; A[:p//2, 1] = 0.1
A[p//2:, 0] = 0.1; A[p//2:, 1] = 1.0
X_true = np.outer(s1, A[:,0]) + np.outer(s2, A[:,1]) + rng.normal(0, 0.05, (n, p))

# Logistic detection model
log_abundance = np.log(np.maximum(X_true - X_true.min() + 0.1, 1e-3))
beta0, beta1 = 4.0, 1.5
det_prob = 1.0 / (1.0 + np.exp(-(beta0 + beta1 * log_abundance)))
mask = rng.uniform(0, 1, (n, p)) < det_prob   # True == detected
X_obs = np.where(mask, X_true, np.nan)

header = f"# generated by python {platform.python_version()} numpy {np.__version__} seed=7 beta0=4.0 beta1=1.5\n"

# argv[1]: sources (sample_id, source, value)
with open(sys.argv[1], 'w') as f:
    f.write(header)
    f.write("sample_id\tsource\tvalue\n")
    for i in range(n):
        f.write(f"S{i:02d}\tsource_1\t{s1[i]:.10f}\n")
        f.write(f"S{i:02d}\tsource_2\t{s2[i]:.10f}\n")

# argv[2]: observed abundance, NaN where below detection
with open(sys.argv[2], 'w') as f:
    f.write(header)
    f.write("sample_id\tgene_symbol\tabundance\n")
    for i in range(n):
        for j in range(p):
            v = X_obs[i,j]
            f.write(f"S{i:02d}\tG{j:03d}\t{'NaN' if np.isnan(v) else f'{v:.10f}'}\n")

# argv[3]: detection mask (0/1)
with open(sys.argv[3], 'w') as f:
    f.write(header)
    f.write("sample_id\tgene_symbol\tdetected\n")
    for i in range(n):
        for j in range(p):
            f.write(f"S{i:02d}\tG{j:03d}\t{1 if mask[i,j] else 0}\n")

# argv[4]: ground-truth curve coefficients (used by F2 to verify atman recovers them)
with open(sys.argv[4], 'w') as f:
    f.write(header)
    f.write("beta0\tbeta1\n")
    f.write("4.0\t1.5\n")
