"""Generate an NMF KL-divergence reference using sklearn.

Outputs:
  argv[1]: nmf_kl_reference.tsv — loadings TSV with columns
           program\tassay_id\tgene_symbol\tloading
           matching the existing ICA loadings schema (see crates/atman/src/
           commands/decompose.rs:1526) so align programs / bootstrap / project
           can consume NMF outputs unchanged.

Pinned: random_state=42, init='nndsvda', solver='mu', beta_loss='kullback-leibler',
n_components=4, max_iter=400, tol=1e-6.
"""

import sys
import platform
import numpy as np
import sklearn
from sklearn.decomposition import NMF

# Synthetic non-negative ground truth: 30 samples, 50 genes, 4 latent factors.
rng = np.random.default_rng(123)
W_true = rng.gamma(2.0, 1.0, size=(30, 4))
H_true = rng.gamma(1.0, 1.0, size=(4, 50))
X = W_true @ H_true + rng.gamma(0.5, 0.2, size=(30, 50))

model = NMF(
    n_components=4, init="nndsvda", solver="mu",
    beta_loss="kullback-leibler", max_iter=400, tol=1e-6, random_state=42,
)
W = model.fit_transform(X)
H = model.components_

# Loadings reference (4-column schema matching ICA loadings)
with open(sys.argv[1], "w") as f:
    f.write(f"# generated by sklearn {sklearn.__version__} numpy {np.__version__} "
            f"python {platform.python_version()}\n")
    f.write("program\tassay_id\tgene_symbol\tloading\n")
    for k in range(H.shape[0]):
        for j in range(H.shape[1]):
            assay_id = j + 1     # 1-based
            f.write(f"program_{k+1:02d}\t{assay_id}\tG{j:03d}\t{H[k,j]:.10f}\n")
